category: システム環境・エコロジー
sub_categories:
  - name: システム制約/前提条件
    items:
      - id: F.1.1.1
        name: 構築時の制約条件
        description: |-
          構築時の制約となる社内基準や法令、各地方自治体の条例などの制約が存在しているかの項目。
          例）
          ・J-SOX法
          ・ISO/IEC27000系
          ・政府機関の情報セキュリティ対策のための統一基準
          ・FISC
          ・プライバシーマーク
          ・構築実装場所の制限
          など
        metrics: 構築時の制約条件
        levels:
          '0': 制約無し
          '1': 制約有り(重要な制約のみ適用)
          '2': 制約有り(全ての制約を適用)
        model_case_levels:
          low_impact: 0
          mid_impact: 1
          high_impact: 1
      - id: F.1.2.1
        name: 運用時の制約条件
        description: |-
          運用時の制約となる社内基準や法令、各地方自治体の条例などの制約が存在しているかの項目。
          例）
          ・J-SOX法
          ・ISO/IEC27000系
          ・政府機関の情報セキュリティ対策のための統一基準
          ・FISC
          ・プライバシーマーク
          ・リモートからの運用の可否
          など
        metrics: 運用時の制約条件
        levels:
          '0': 制約無し
          '1': 制約有り(重要な制約のみ適用)
          '2': 制約有り(全ての制約を適用)
        model_case_levels:
          low_impact: 0
          mid_impact: 1
          high_impact: 1
  - name: システム特性
    items:
      - id: F.2.1.1
        name: ユーザ数
        description: システムを使用する利用者(エンドユーザ)の人数。
        metrics: ユーザ数
        levels:
          '0': 特定ユーザのみ
          '1': 上限が決まっている
          '2': 不特定多数のユーザが利用
        model_case_levels:
          low_impact: 0
          mid_impact: 1
          high_impact: 2
      - id: F.2.2.1
        name: クライアント数
        description: システムで使用され、管理しなければいけないクライアントの数。
        metrics: クライアント数
        levels:
          '0': 特定クライアントのみ
          '1': 上限が決まっている
          '2': 不特定多数のクライアントが利用
        model_case_levels:
          low_impact: 0
          mid_impact: 1
          high_impact: 1
      - id: F.2.3.1
        name: 拠点数
        description: システムが稼働する拠点の数。
        metrics: 拠点数
        levels:
          '0': 単一拠点
          '1': 複数拠点
        model_case_levels:
          low_impact: 0
          mid_impact: 1
          high_impact: 1
      - id: F.2.4.1
        name: 地域的広がり
        description: システムが稼働する地域的な広がり。
        metrics: 地域的広がり
        levels:
          '0': 拠点内
          '1': 同一都市内
          '2': 同一都道府県内
          '3': 同一地方
          '4': 国内
          '5': 海外
        model_case_levels:
          low_impact: 0
          mid_impact: 0
          high_impact: 4
      - id: F.2.5.1
        name: 特定製品指定
        description: ユーザの指定によるオープンソース製品や第三者製品(ISV/IHV)などの採用の有無を確認する項目。採用によりサポート難易度への影響があるかの視点で確認を行う。
        metrics: 特定製品の採用有無
        levels:
          '0': 特定製品の指定がない
          '1': 一部に特定製品の指定がある
          '2': サポートが困難な製品の指定がある
        model_case_levels:
          low_impact: 0
          mid_impact: 1
          high_impact: 0
      - id: F.2.6.1
        name: システム利用範囲
        description: システム利用者が属する属性の広がり。
        metrics: システム利用範囲
        levels:
          '0': 部門内のみ
          '1': 社内のみ
          '2': 社外(BtoB)
          '3': 社外（BtoC）
        model_case_levels: {}
      - id: F.2.7.1
        name: 複数言語対応
        description: システム構築の上で使用が必要、またはサービスとして提供しなければならない言語。扱わなければならない言語の数や各言語スキル保持者へのアクセシビリティを考慮。
        metrics: 言語数
        levels:
          '0': 数値などのみ扱う
          '1': '1'
          '2': '2'
          '3': '5'
          '4': '10'
          '5': '100'
        model_case_levels: {}
  - name: 適合規格
    items:
      - id: F.3.1.1
        name: 製品安全規格
        description: 提供するシステムに使用する製品について、UL60950などの製品安全規格を取得していることを要求されているかを確認する項目。
        metrics: 規格取得の有無
        levels:
          '0': 規格取得の必要無し
          '1': UL60950相当取得
        model_case_levels:
          low_impact: 0
          mid_impact: 1
          high_impact: 0
      - id: F.3.2.1
        name: 環境保護
        description: 提供するシステムに使用する製品について、RoHS指令などの特定有害物質の使用制限についての規格の取得を要求されているかを確認する項目。
        metrics: 規格取得の有無
        levels:
          '0': 規格取得の必要無し
          '1': RoHS指令相当取得
        model_case_levels:
          low_impact: 0
          mid_impact: 1
          high_impact: 0
      - id: F.3.3.1
        name: 電磁干渉
        description: 提供するシステムに使用する製品について、VCCIなどの機器自身が放射する電磁波をある一定以下のレベルに抑える規格を取得していることを要求されているかを確認する項目。
        metrics: 規格取得の有無
        levels:
          '0': 規格取得の必要無し
          '1': VCCI ClassA取得
          '2': VCCI ClassB取得
        model_case_levels: {}
  - name: 機材設置環境条件
    items:
      - id: F.4.1.1
        name: 耐震/免震
        description: 地震発生時にシステム設置環境で耐える必要のある実効的な最大震度を規定。建屋が揺れを減衰するなどの工夫により、外部は震度7超でも設置環境では実効的に最大震度4程度になる場合には震度4よりレベルを設定する。なお、想定以上の揺れではサービスを継続しないでも良い場合には、その想定震度でレベルを設定する。
        metrics: 耐震震度
        levels:
          '0': 対策不要
          '1': 震度4相当（50ガル）
          '2': 震度5弱相当（100ガル）
          '3': 震度6弱相当（250ガル）
          '4': 震度6強相当（500ガル）
          '5': 震度7相当（1000ガル）
        model_case_levels:
          low_impact: 2
          mid_impact: 3
          high_impact: 4
      - id: F.4.2.1
        name: スペース
        description: どの程度の床面積(WxD)/高さが必要かの項目。保守作業用スペースについても考慮する。また、移行時には新旧システムが並行稼働可能なスペースの確保が可能か否かについても確認が必要である。可能であれば事前確認を実施する。
        metrics: 設置スペース制限(マシンルーム)
        levels:
          '0': スペースに関する制限無し
          '1': フロア設置用機材を用いて構成
          '2': ラックマウント用機材を用いて構成
        model_case_levels:
          low_impact: 2
          mid_impact: 2
          high_impact: 2
      - id: F.4.2.2
        name: スペース
        description: どの程度の床面積(WxD)/高さが必要かの項目。保守作業用スペースについても考慮する。また、移行時には新旧システムが並行稼働可能なスペースの確保が可能か否かについても確認が必要である。可能であれば事前確認を実施する。
        metrics: 設置スペース制限(事務所設置)
        levels:
          '0': スペースに関する制限無し
          '1': 専用のスペースを割当て可能
          '2': 人と混在するスペースに設置必要
        model_case_levels:
          low_impact: 1
          mid_impact: 2
          high_impact: 2
      - id: F.4.2.3
        name: スペース
        description: どの程度の床面積(WxD)/高さが必要かの項目。保守作業用スペースについても考慮する。また、移行時には新旧システムが並行稼働可能なスペースの確保が可能か否かについても確認が必要である。可能であれば事前確認を実施する。
        metrics: 並行稼働スペース(移行時)
        levels:
          '0': 専用スペースの確保が可能
          '1': 共用スペースの確保が可能
          '2': 確保不可
        model_case_levels: {}
      - id: F.4.2.4
        name: スペース
        description: どの程度の床面積(WxD)/高さが必要かの項目。保守作業用スペースについても考慮する。また、移行時には新旧システムが並行稼働可能なスペースの確保が可能か否かについても確認が必要である。可能であれば事前確認を実施する。
        metrics: 設置スペースの拡張余地
        levels:
          '0': 十分な拡張余地有り
          '1': 一部制約有り(既製品で対応できるレベル)
          '2': 制約有り(特注対応や工事が必要)
        model_case_levels: {}
      - id: F.4.3.1
        name: 重量
        description: 建物の床荷重を考慮した設置設計が必要となることを確認する項目。低い床荷重の場合ほど、設置のための対策が必要となる可能性が高い。
        metrics: 床荷重
        levels:
          '0': 2,000Kg/㎡以上
          '1': 1,200Kg/㎡
          '2': 800Kg/㎡
          '3': 500Kg/㎡
          '4': 300Kg/㎡
          '5': 200Kg/㎡
        model_case_levels: {}
      - id: F.4.3.2
        name: 重量
        description: 建物の床荷重を考慮した設置設計が必要となることを確認する項目。低い床荷重の場合ほど、設置のための対策が必要となる可能性が高い。
        metrics: 設置対策
        levels:
          '0': 不要
          '1': 荷重を分散するための資材(鉄板など)を配備する
          '2': ラック当りの重量を制限して、分散構成を採る
          '3': 設置環境固有の条件(梁の場所など)を考慮して、設置設計を行う
        model_case_levels: {}
      - id: F.4.4.1
        name: 電気設備適合性
        description: ユーザが提供する設置場所の電源条件(電源電圧/電流/周波数/相数/系統数/無停止性/必要工事規模など)と導入システムの適合性に関する項目。同時に空調についても評価対象とする。また、移行時の並行稼動が可能か否かについても確認が必要である。可能であれば事前確認を実施する。
        metrics: 供給電力適合性
        levels:
          '0': 現状の設備で特に制限無し
          '1': 電源工事は必要だが、分電盤改造など二次側の工事のみで対応可能
          '2': 電源工事は必要だが、一次、二次とも工事可能
          '3': 工事などができず、規模に対して容量が少し足りない
          '4': まったく対応できず、設置場所を再考する必要がある
        model_case_levels: {}
      - id: F.4.4.2
        name: 電気設備適合性
        description: ユーザが提供する設置場所の電源条件(電源電圧/電流/周波数/相数/系統数/無停止性/必要工事規模など)と導入システムの適合性に関する項目。同時に空調についても評価対象とする。また、移行時の並行稼動が可能か否かについても確認が必要である。可能であれば事前確認を実施する。
        metrics: 電源容量の制約
        levels:
          '0': 制約無し(必要な電源容量の確保が可能)
          '1': 制約有り(既製品で対応できるレベル)
          '2': 制約有り(カスタマイズや工事が必要)
        model_case_levels: {}
      - id: F.4.4.3
        name: 電気設備適合性
        description: ユーザが提供する設置場所の電源条件(電源電圧/電流/周波数/相数/系統数/無停止性/必要工事規模など)と導入システムの適合性に関する項目。同時に空調についても評価対象とする。また、移行時の並行稼動が可能か否かについても確認が必要である。可能であれば事前確認を実施する。
        metrics: 並行稼働電力(移行時)
        levels:
          '0': 全面的に確保が可能
          '1': 部分的に確保が可能
          '2': 確保が困難
        model_case_levels: {}
      - id: F.4.4.4
        name: 電気設備適合性
        description: ユーザが提供する設置場所の電源条件(電源電圧/電流/周波数/相数/系統数/無停止性/必要工事規模など)と導入システムの適合性に関する項目。同時に空調についても評価対象とする。また、移行時の並行稼動が可能か否かについても確認が必要である。可能であれば事前確認を実施する。
        metrics: 停電対策
        levels:
          '0': 無し
          '1': 瞬断(10ms程度)
          '2': 10分
          '3': 1時間
          '4': 1日間
          '5': 1週間
        model_case_levels: {}
      - id: F.4.4.5
        name: 電気設備適合性
        description: ユーザが提供する設置場所の電源条件(電源電圧/電流/周波数/相数/系統数/無停止性/必要工事規模など)と導入システムの適合性に関する項目。同時に空調についても評価対象とする。また、移行時の並行稼動が可能か否かについても確認が必要である。可能であれば事前確認を実施する。
        metrics: 想定設置場所の電圧変動
        levels:
          '0': ±10%以下
          '1': ±10%を超える
        model_case_levels: {}
      - id: F.4.4.6
        name: 電気設備適合性
        description: ユーザが提供する設置場所の電源条件(電源電圧/電流/周波数/相数/系統数/無停止性/必要工事規模など)と導入システムの適合性に関する項目。同時に空調についても評価対象とする。また、移行時の並行稼動が可能か否かについても確認が必要である。可能であれば事前確認を実施する。
        metrics: 想定設置場所の周波数変動
        levels:
          '0': ±2%以下
          '1': ±2%を超える
        model_case_levels: {}
      - id: F.4.4.7
        name: 電気設備適合性
        description: ユーザが提供する設置場所の電源条件(電源電圧/電流/周波数/相数/系統数/無停止性/必要工事規模など)と導入システムの適合性に関する項目。同時に空調についても評価対象とする。また、移行時の並行稼動が可能か否かについても確認が必要である。可能であれば事前確認を実施する。
        metrics: 接地
        levels:
          '0': 接地不要
          '1': 接地が必要
          '2': 専用接地が必要
        model_case_levels: {}
      - id: F.4.5.1
        name: 温度（帯域）
        description: |-
          システムが稼働すべき環境温度の帯域条件。
          周囲環境によってはシステムを正常稼動させるには特別な対策が必要となることがある。
        metrics: 温度（帯域）
        levels:
          '0': 対策不要
          '1': 16度から32度(多くのテープ装置の稼働可能条件)
          '2': 5度から35度(多くの機器の稼働可能条件)
          '3': 0度～40度
          '4': 0度～60度
          '5': '-30度～80度'
        model_case_levels: {}
      - id: F.4.6.1
        name: 湿度（帯域）
        description: |-
          システムが稼働すべき環境湿度の帯域条件。
          周囲環境によってはシステムを正常稼動させるには特別な対策が必要となることがある。
        metrics: 湿度（帯域）
        levels:
          '0': 対策不要
          '1': 45%～55%
          '2': 20%～80%
          '3': 0%～85%
          '4': 結露無し条件のみ
        model_case_levels: {}
      - id: F.4.7.1
        name: 空調性能
        description: システムを稼働させるのに十分な冷却能力を保持し、特定のホットスポットが存在する場合にはそれを考慮した冷気供給を行える能力。
        metrics: 空調性能
        levels:
          '0': 十分な余力有り
          '1': ホットスポットなどへの部分的な対策が必要
          '2': 能力が不足しており、対策が必要
        model_case_levels: {}
      - id: F.4.7.2
        name: 空調性能
        description: システムを稼働させるのに十分な冷却能力を保持し、特定のホットスポットが存在する場合にはそれを考慮した冷気供給を行える能力。
        metrics: 空調設備の制約
        levels:
          '0': 制約無し(必要な空調の確保が可能)
          '1': 制約有り(既製品で対応できるレベル)
          '2': 制約有り(カスタマイズや工事が必要)
        model_case_levels: {}
  - name: 環境マネージメント
    items:
      - id: F.5.1.1
        name: 環境負荷を抑える工夫
        description: |-
          環境負荷を最小化する工夫の度合いの項目。
          例えば、グリーン購入法適合製品の購入など、環境負荷の少ない機材・消耗品を採用する。
          また、ライフサイクルを通じた廃棄材の最小化の検討を行う。例えば、拡張の際に既設機材の廃棄が不要で、必要な部材の増設、入れ替えのみで対応可能な機材を採用するなどである。また、ライフサイクルが長い機材ほど廃棄材は少ないと解釈できる。
        metrics: グリーン購入法対応度
        levels:
          '0': 対処不要
          '1': グリーン購入法の基準を満たす製品を一部使用
          '2': グリーン購入法の基準を満たす製品のみを使用
        model_case_levels: {}
      - id: F.5.1.2
        name: 環境負荷を抑える工夫
        description: |-
          環境負荷を最小化する工夫の度合いの項目。
          例えば、グリーン購入法適合製品の購入など、環境負荷の少ない機材・消耗品を採用する。
          また、ライフサイクルを通じた廃棄材の最小化の検討を行う。例えば、拡張の際に既設機材の廃棄が不要で、必要な部材の増設、入れ替えのみで対応可能な機材を採用するなどである。また、ライフサイクルが長い機材ほど廃棄材は少ないと解釈できる。
        metrics: 同一機材拡張余力
        levels:
          '0': 無し
          '1': 2倍
          '2': 4倍
          '3': 10倍
          '4': 30倍
          '5': 100倍以上
        model_case_levels: {}
      - id: F.5.1.3
        name: 環境負荷を抑える工夫
        description: |-
          環境負荷を最小化する工夫の度合いの項目。
          例えば、グリーン購入法適合製品の購入など、環境負荷の少ない機材・消耗品を採用する。
          また、ライフサイクルを通じた廃棄材の最小化の検討を行う。例えば、拡張の際に既設機材の廃棄が不要で、必要な部材の増設、入れ替えのみで対応可能な機材を採用するなどである。また、ライフサイクルが長い機材ほど廃棄材は少ないと解釈できる。
        metrics: 機材のライフサイクル期間
        levels:
          '0': 3年
          '1': 5年
          '2': 7年
          '3': 10年以上
        model_case_levels: {}
      - id: F.5.2.1
        name: エネルギー消費効率
        description: |-
          本来はシステムの仕事量をそのエネルギー消費量で除した単位エネルギー当りの仕事量のこと。ただし、汎用的な仕事量の定義が存在しないため、効率を直接求めることは困難である。また、同じ仕事を行う別のシステムも存在しないことが多いため、比較自体も困難である。このため、エネルギー消費効率に関しては、少し視点を変えて、ユーザからの目標値の提示の有無などでレベル化を行っている。なお、電力エネルギーを前提とするシステムでは、消費電力≒発熱量である。
          また、システムの仕事量の視点ではなく、データセンターのエネルギー効率を示す指標にPUE(Power Usage Effectiveness)や、DPPE(Datacenter Performance Per Energy)などがある。
        metrics: エネルギー消費の目標値
        levels:
          '0': 目標値無し
          '1': 目標値の提示有り
          '2': 目標値の提示が有り、更なる追加削減の要求も有る
        model_case_levels: {}
      - id: F.5.3.1
        name: CO2排出量
        description: システムのライフサイクルを通じて排出されるCO2の量。ただし、単純なCO2排出量でレベル化するのは困難であるため、少し視点を変えて、ユーザからの目標値の提示の有無などでレベル化を行っている。
        metrics: CO2排出量の目標値
        levels:
          '0': 目標値の設定不要
          '1': 目標値の提示有り
          '2': 目標値の提示が有り、更なる追加削減の要求も有る
        model_case_levels: {}
      - id: F.5.4.1
        name: 低騒音
        description: 機器から発生する騒音の低さの項目。特にオフィス設置の場合などには要求度が高くなる傾向がある。また、データセンターなどに設置する場合でも一定以上の騒音の発生は労働環境として問題となることがある。
        metrics: 騒音値
        levels:
          '0': 対策不要
          '1': 87dB(英国RoSPAの騒音基準による防音保護具の使用も考慮に入れた許容限界値)以下
          '2': 85dB(英国RoSPAの騒音基準による第2アクションレベル)以下
          '3': 80dB(英国RoSPAの騒音基準による第1アクションレベル)以下
          '4': 40dB(図書館レベル)以下
          '5': 35dB(寝室レベル)以下
        model_case_levels: {}
