category: セキュリティ
sub_categories:
  - name: 前提条件・制約条件
    items:
      - id: E.1.1.1
        name: 情報セキュリティに関するコンプライアンス
        description: |-
          順守すべき情報セキュリティに関する組織規程やルール、法令、ガイドライン等が存在するかどうかを確認するための項目。
          なお、順守すべき規程等が存在する場合は、規定されている内容と矛盾が生じないよう対策を検討する。
          例）
          ・国内/海外の法律
          ・資格認証
          ・ガイドライン
          ・その他ルール
        metrics: 順守すべき社内規程、ルール、法令、ガイドライン等の有無
        levels:
          '0': 無し
          '1': 有り
        model_case_levels:
          low_impact: 0
          mid_impact: 0
          high_impact: 0
  - name: セキュリティリスク分析
    items:
      - id: E.2.1.1
        name: セキュリティリスク分析
        description: |-
          システム開発を実施する中で、どの範囲で対象システムの脅威を洗い出し、影響の分析を実施するかの方針を確認するための項目。
          なお、適切な範囲を設定するためには、資産の洗い出しやデータのライフサイクルの確認等を行う必要がある。
          また、洗い出した脅威に対して、対策する範囲を検討する。
        metrics: リスク分析範囲
        levels:
          '0': 分析なし
          '1': 重要度が高い資産を扱う範囲、あるいは、外接部分
          '2': 開発範囲
        model_case_levels:
          low_impact: 0
          mid_impact: 1
          high_impact: 2
  - name: セキュリティ診断
    items:
      - id: E.3.1.1
        name: セキュリティ診断
        description: 対象システムや、各種ドキュメント（設計書や環境定義書、実装済みソフトウェアのソースコードなど）に対して、セキュリティに特化した各種試験や検査の実施の有無を確認するための項目。
        metrics: ネットワーク診断実施の有無
        levels:
          '0': 無し
          '1': 有り
        model_case_levels:
          low_impact: 1
          mid_impact: 1
          high_impact: 1
      - id: E.3.1.2
        name: セキュリティ診断
        description: 対象システムや、各種ドキュメント（設計書や環境定義書、実装済みソフトウェアのソースコードなど）に対して、セキュリティに特化した各種試験や検査の実施の有無を確認するための項目。
        metrics: Web診断実施の有無
        levels:
          '0': 無し
          '1': 有り
        model_case_levels:
          low_impact: 1
          mid_impact: 1
          high_impact: 1
      - id: E.3.1.3
        name: セキュリティ診断
        description: 対象システムや、各種ドキュメント（設計書や環境定義書、実装済みソフトウェアのソースコードなど）に対して、セキュリティに特化した各種試験や検査の実施の有無を確認するための項目。
        metrics: DB診断実施の有無
        levels:
          '0': 無し
          '1': 有り
        model_case_levels: {}
  - name: セキュリティリスク管理
    items:
      - id: E.4.1.1
        name: セキュリティリスクの見直し
        description: |-
          対象システムにおいて、運用開始後に新たに発見された脅威の洗い出しとその影響の分析をどの範囲で実施するかを確認するための項目。
          セキュリティリスクの見直しには、セキュリティホールや脆弱性、新たな脅威の調査等が含まれる。
        metrics: セキュリティリスク見直し頻度
        levels:
          '0': 無し
          '1': セキュリティに関するイベントの発生時に実施（随時）
          '2': |-
            セキュリティに関するイベントの発生時に実施（随時）
            ＋
            定期的に実施
        model_case_levels: {}
      - id: E.4.1.2
        name: セキュリティリスクの見直し
        description: |-
          対象システムにおいて、運用開始後に新たに発見された脅威の洗い出しとその影響の分析をどの範囲で実施するかを確認するための項目。
          セキュリティリスクの見直しには、セキュリティホールや脆弱性、新たな脅威の調査等が含まれる。
        metrics: セキュリティリスクの見直し範囲
        levels:
          '0': 分析なし
          '1': 重要度が高い資産を扱う範囲、あるいは、外接部分
          '2': システム全体
        model_case_levels: {}
      - id: E.4.2.1
        name: セキュリティリスク対策の見直し
        description: |-
          対象システムにおいて、運用開始後に発見された脅威に対する対策の方針を確認するための項目。
          また、検討するにあたり、発見された脅威についての対応範囲について明らかにする。
        metrics: 運用開始後のリスク対応範囲
        levels:
          '0': 対応しない
          '1': 重要度が高い資産に関連する、あるいは、外接部分の脅威に対応
          '2': 洗い出した脅威全体に対応
        model_case_levels: {}
      - id: E.4.2.2
        name: セキュリティリスク対策の見直し
        description: |-
          対象システムにおいて、運用開始後に発見された脅威に対する対策の方針を確認するための項目。
          また、検討するにあたり、発見された脅威についての対応範囲について明らかにする。
        metrics: リスク対策方針
        levels:
          '0': 無し
          '1': 有り
        model_case_levels: {}
      - id: E.4.3.1
        name: セキュリティパッチ適用
        description: |-
          対象システムの脆弱性等に対応するためのセキュリティパッチ適用に関する適用範囲、方針および適用のタイミングを確認するための項目。
          これらのセキュリティパッチには、ウィルス定義ファイル等を含む。
          また、セキュリティパッチの適用範囲は、OS、ミドルウェア等毎に確認する必要があり、これらセキュリティパッチの適用を検討する際には、システム全体への影響を確認し、パッチ適用の可否を判断する必要がある。
          なお、影響の確認等については保守契約の内容として明記されることが望ましい。
        metrics: セキュリティパッチ適用範囲
        levels:
          '0': セキュリティパッチを適用しない
          '1': 重要度が高い資産を扱う範囲、あるいは、外接部分
          '2': システム全体
        model_case_levels: {}
      - id: E.4.3.2
        name: セキュリティパッチ適用
        description: |-
          対象システムの脆弱性等に対応するためのセキュリティパッチ適用に関する適用範囲、方針および適用のタイミングを確認するための項目。
          これらのセキュリティパッチには、ウィルス定義ファイル等を含む。
          また、セキュリティパッチの適用範囲は、OS、ミドルウェア等毎に確認する必要があり、これらセキュリティパッチの適用を検討する際には、システム全体への影響を確認し、パッチ適用の可否を判断する必要がある。
          なお、影響の確認等については保守契約の内容として明記されることが望ましい。
        metrics: セキュリティパッチ適用方針
        levels:
          '0': セキュリティパッチを適用しない
          '1': 緊急性の高いセキュリティパッチのみ適用
          '2': 全てのセキュリティパッチを適用
        model_case_levels: {}
      - id: E.4.3.3
        name: セキュリティパッチ適用
        description: |-
          対象システムの脆弱性等に対応するためのセキュリティパッチ適用に関する適用範囲、方針および適用のタイミングを確認するための項目。
          これらのセキュリティパッチには、ウィルス定義ファイル等を含む。
          また、セキュリティパッチの適用範囲は、OS、ミドルウェア等毎に確認する必要があり、これらセキュリティパッチの適用を検討する際には、システム全体への影響を確認し、パッチ適用の可否を判断する必要がある。
          なお、影響の確認等については保守契約の内容として明記されることが望ましい。
        metrics: セキュリティパッチ適用タイミング
        levels:
          '0': セキュリティパッチを適用しない
          '1': 障害パッチ適用時に合わせて実施
          '2': 定期保守時に実施
          '3': パッチ出荷時に実施
        model_case_levels: {}
  - name: アクセス・利用制限
    items:
      - id: E.5.1.1
        name: 認証機能
        description: |-
          資産を利用する主体（利用者や機器等）を識別するための認証を実施するか、また、どの程度実施するのかを確認するための項目。
          複数回の認証を実施することにより、抑止効果を高めることができる。
          なお、認証するための方式としては、ID/パスワードによる認証や、ICカード等を用いた認証等がある。
        metrics: 管理権限を持つ主体の認証
        levels:
          '0': 実施しない
          '1': 1回
          '2': 複数回の認証
          '3': 複数回、異なる方式による認証
        model_case_levels:
          low_impact: 1
          mid_impact: 2
          high_impact: 2
      - id: E.5.1.2
        name: 認証機能
        description: |-
          資産を利用する主体（利用者や機器等）を識別するための認証を実施するか、また、どの程度実施するのかを確認するための項目。
          複数回の認証を実施することにより、抑止効果を高めることができる。
          なお、認証するための方式としては、ID/パスワードによる認証や、ICカード等を用いた認証等がある。
        metrics: 管理権限を持たない主体の認証
        levels:
          '0': 実施しない
          '1': 1回
          '2': 複数回の認証
          '3': 複数回、異なる方式による認証
        model_case_levels: {}
      - id: E.5.2.1
        name: 利用制限
        description: |-
          認証された主体（利用者や機器など）に対して、資産の利用等を、ソフトウェアやハードウェアにより制限するか確認するための項目。
          例） ドアや保管庫の施錠、USBやCD-RWやキーボードなどの入出力デバイスの制限、コマンド実行制限など。
        metrics: システム上の対策における操作制限度
        levels:
          '0': 無し
          '1': 必要最小限のプログラムの実行、コマンドの操作、ファイルへのアクセスのみを許可
        model_case_levels:
          low_impact: 1
          mid_impact: 1
          high_impact: 1
      - id: E.5.2.2
        name: 利用制限
        description: |-
          認証された主体（利用者や機器など）に対して、資産の利用等を、ソフトウェアやハードウェアにより制限するか確認するための項目。
          例） ドアや保管庫の施錠、USBやCD-RWやキーボードなどの入出力デバイスの制限、コマンド実行制限など。
        metrics: 物理的な対策による操作制限度
        levels:
          '0': 無し
          '1': 必要最小限のハードウェアの利用や操作のみを許可
        model_case_levels: {}
      - id: E.5.3.1
        name: 管理方法
        description: 認証に必要な情報（例えば、 ID/パスワード、指紋、虹彩、静脈など、主体を一意に特定する情報）の追加、更新、削除等のルール策定を実施するかを確認するための項目。
        metrics: 管理ルールの策定
        levels:
          '0': 実施しない
          '1': 実施する
        model_case_levels: {}
  - name: データの秘匿
    items:
      - id: E.6.1.1
        name: データ暗号化
        description: 機密性のあるデータを、伝送時や蓄積時に秘匿するための暗号化を実施するかを確認するための項目。
        metrics: 伝送データの暗号化の有無
        levels:
          '0': 無し
          '1': 認証情報のみ暗号化
          '2': 重要情報を暗号化
        model_case_levels:
          low_impact: 1
          mid_impact: 2
          high_impact: 2
      - id: E.6.1.2
        name: データ暗号化
        description: 機密性のあるデータを、伝送時や蓄積時に秘匿するための暗号化を実施するかを確認するための項目。
        metrics: 蓄積データの暗号化の有無
        levels:
          '0': 無し
          '1': 認証情報のみ暗号化
          '2': 重要情報を暗号化
        model_case_levels:
          low_impact: 1
          mid_impact: 2
          high_impact: 2
      - id: E.6.1.3
        name: データ暗号化
        description: 機密性のあるデータを、伝送時や蓄積時に秘匿するための暗号化を実施するかを確認するための項目。
        metrics: 鍵管理
        levels:
          '0': 無し
          '1': ソフトウェアによる鍵管理
          '2': 耐タンパデバイスによる鍵管理
        model_case_levels: {}
  - name: 不正追跡・監視
    items:
      - id: E.7.1.1
        name: 不正監視
        description: |-
          不正行為を検知するために、それらの不正について監視する範囲や、監視の記録を保存する量や期間を確認するための項目。
          なお、どのようなログを取得する必要があるかは、実現するシステムやサービスに応じて決定する必要がある。
          また、ログを取得する場合には、不正監視対象と併せて、取得したログのうち、確認する範囲を定める必要がある。
        metrics: ログの取得
        levels:
          '0': 実施しない
          '1': 実施する
        model_case_levels:
          low_impact: 1
          mid_impact: 1
          high_impact: 1
      - id: E.7.1.2
        name: 不正監視
        description: |-
          不正行為を検知するために、それらの不正について監視する範囲や、監視の記録を保存する量や期間を確認するための項目。
          なお、どのようなログを取得する必要があるかは、実現するシステムやサービスに応じて決定する必要がある。
          また、ログを取得する場合には、不正監視対象と併せて、取得したログのうち、確認する範囲を定める必要がある。
        metrics: ログ保管期間
        levels:
          '0': 6ヶ月
          '1': 1年
          '2': 3年
          '3': 5年
          '4': 10年以上有期
          '5': 永久保管
        model_case_levels:
          low_impact: 0
          mid_impact: 2
          high_impact: 3
      - id: E.7.1.3
        name: 不正監視
        description: |-
          不正行為を検知するために、それらの不正について監視する範囲や、監視の記録を保存する量や期間を確認するための項目。
          なお、どのようなログを取得する必要があるかは、実現するシステムやサービスに応じて決定する必要がある。
          また、ログを取得する場合には、不正監視対象と併せて、取得したログのうち、確認する範囲を定める必要がある。
        metrics: 不正監視対象（装置）
        levels:
          '0': 無し
          '1': 重要度が高い資産を扱う範囲、あるいは、外接部分
          '2': システム全体
        model_case_levels:
          low_impact: 1
          mid_impact: 1
          high_impact: 2
      - id: E.7.1.4
        name: 不正監視
        description: |-
          不正行為を検知するために、それらの不正について監視する範囲や、監視の記録を保存する量や期間を確認するための項目。
          なお、どのようなログを取得する必要があるかは、実現するシステムやサービスに応じて決定する必要がある。
          また、ログを取得する場合には、不正監視対象と併せて、取得したログのうち、確認する範囲を定める必要がある。
        metrics: 不正監視対象（ネットワーク）
        levels:
          '0': 無し
          '1': 重要度が高い資産を扱う範囲、あるいは、外接部分
          '2': システム全体
        model_case_levels:
          low_impact: 1
          mid_impact: 1
          high_impact: 2
      - id: E.7.1.5
        name: 不正監視
        description: |-
          不正行為を検知するために、それらの不正について監視する範囲や、監視の記録を保存する量や期間を確認するための項目。
          なお、どのようなログを取得する必要があるかは、実現するシステムやサービスに応じて決定する必要がある。
          また、ログを取得する場合には、不正監視対象と併せて、取得したログのうち、確認する範囲を定める必要がある。
        metrics: 不正監視対象（侵入者・不正操作等）
        levels:
          '0': 無し
          '1': 重要度が高い資産を扱う範囲、あるいは、外接部分
          '2': システム全体
        model_case_levels:
          low_impact: 1
          mid_impact: 1
          high_impact: 2
      - id: E.7.1.6
        name: 不正監視
        description: |-
          不正行為を検知するために、それらの不正について監視する範囲や、監視の記録を保存する量や期間を確認するための項目。
          なお、どのようなログを取得する必要があるかは、実現するシステムやサービスに応じて決定する必要がある。
          また、ログを取得する場合には、不正監視対象と併せて、取得したログのうち、確認する範囲を定める必要がある。
        metrics: 確認間隔
        levels:
          '0': 無し
          '1': セキュリティに関するイベントの発生時に実施（随時）
          '2': |-
            セキュリティに関するイベントの発生時に実施（随時）
            ＋
            定期的に実施
          '3': 常時確認
        model_case_levels: {}
      - id: E.7.2.1
        name: データ検証
        description: 情報が正しく処理されて保存されていることを証明可能とし、情報の改ざんを検知するための仕組みとしてデジタル署名を導入するかを確認するための項目。
        metrics: デジタル署名の利用の有無
        levels:
          '0': 無し
          '1': 有り
        model_case_levels: {}
      - id: E.7.2.2
        name: データ検証
        description: 情報が正しく処理されて保存されていることを証明可能とし、情報の改ざんを検知するための仕組みとしてデジタル署名を導入するかを確認するための項目。
        metrics: 確認間隔
        levels:
          '0': 無し
          '1': セキュリティに関するイベントの発生時に実施（随時）
          '2': |-
            セキュリティに関するイベントの発生時に実施（随時）
            ＋
            定期的に実施
          '3': 常時確認
        model_case_levels: {}
  - name: ネットワーク対策
    items:
      - id: E.8.1.1
        name: ネットワーク制御
        description: 不正な通信を遮断するための制御を実施するかを確認するための項目。
        metrics: 通信制御
        levels:
          '0': 無し
          '1': 有り
        model_case_levels:
          low_impact: 1
          mid_impact: 1
          high_impact: 1
      - id: E.8.2.1
        name: 不正検知
        description: ネットワーク上において、不正追跡・監視を実施し、システム内の不正行為や、不正通信を検知する範囲を確認するための項目。
        metrics: 不正通信の検知範囲
        levels:
          '0': 無し
          '1': 重要度が高い資産を扱う範囲、あるいは、外接部分
          '2': システム全体
        model_case_levels:
          low_impact: 1
          mid_impact: 1
          high_impact: 1
      - id: E.8.3.1
        name: サービス停止攻撃の回避
        description: ネットワークへの攻撃による輻輳についての対策を実施するかを確認するための項目。
        metrics: ネットワークの輻輳対策
        levels:
          '0': 無し
          '1': 有り
        model_case_levels:
          low_impact: 1
          mid_impact: 1
          high_impact: 1
  - name: マルウェア対策
    items:
      - id: E.9.1.1
        name: マルウェア対策
        description: |-
          マルウェア（ウィルス、ワーム、ボット等）の感染を防止する、マルウェア対策の実施範囲やチェックタイミングを確認するための項目。
          対策を実施する場合には、ウィルス定義ファイルの更新方法やタイミングについても検討し、常に最新の状態となるようにする必要がある。
        metrics: マルウェア対策実施範囲
        levels:
          '0': 無し
          '1': 重要度が高い資産を扱う範囲、あるいは、外接部分
          '2': システム全体
        model_case_levels:
          low_impact: 1
          mid_impact: 1
          high_impact: 1
      - id: E.9.1.2
        name: マルウェア対策
        description: |-
          マルウェア（ウィルス、ワーム、ボット等）の感染を防止する、マルウェア対策の実施範囲やチェックタイミングを確認するための項目。
          対策を実施する場合には、ウィルス定義ファイルの更新方法やタイミングについても検討し、常に最新の状態となるようにする必要がある。
        metrics: リアルタイムスキャンの実施
        levels:
          '0': 実施しない
          '1': 実施する
        model_case_levels: {}
      - id: E.9.1.3
        name: マルウェア対策
        description: |-
          マルウェア（ウィルス、ワーム、ボット等）の感染を防止する、マルウェア対策の実施範囲やチェックタイミングを確認するための項目。
          対策を実施する場合には、ウィルス定義ファイルの更新方法やタイミングについても検討し、常に最新の状態となるようにする必要がある。
        metrics: フルスキャンの定期チェックタイミング
        levels:
          '0': 無し
          '1': |-
            不定期
            （フルスキャンを行えるタイミングがあれば実施する）
          '2': 1回/月
          '3': 1回/週
          '4': 1回/日
        model_case_levels: {}
  - name: Web対策
    items:
      - id: E.10.1.1
        name: Web実装対策
        description: Webアプリケーション特有の脅威、脆弱性に関する対策を実施するかを確認するための項目。
        metrics: セキュアコーディング、Webサーバの設定等による対策の強化
        levels:
          '0': 無し
          '1': 対策の強化
        model_case_levels:
          low_impact: 1
          mid_impact: 1
          high_impact: 1
      - id: E.10.1.2
        name: Web実装対策
        description: Webアプリケーション特有の脅威、脆弱性に関する対策を実施するかを確認するための項目。
        metrics: WAFの導入の有無
        levels:
          '0': 無し
          '1': 有り
        model_case_levels:
          low_impact: 0
          mid_impact: 0
          high_impact: 1
  - name: セキュリティインシデント対応/復旧
    items:
      - id: E.11.1.1
        name: セキュリティインシデント対応/復旧
        description: セキュリティインシデントが発生した時に、早期発見し、被害の最小化、復旧の支援等をするための体制について確認する項目。
        metrics: セキュリティインシデントの対応体制
        levels:
          '0': 無し
          '1': 有り
        model_case_levels: {}
